import { BeforeModelCallback, FunctionTool, LlmAgent } from '@google/adk';
import { z } from 'zod';
import { DECISION_KEY, VALIDATION_ATTEMPTS_KEY } from './output_keys.js';
import { generateDecisionPrompt } from './prompts/decision.prompt.js';
import { decisionSchema } from './types/index.js';
import { getEvaluationContext, isProjectDetailsFilled } from './utils.js';

const MAX_ITERATIONS = 3;

export const validateDecisionTool = new FunctionTool({
  name: 'validate_decision',
  description: 'Validates the LLM-generated verdict to ensure it is not None. Returns SUCCESS or an ERROR message.',
  parameters: z.object({
    verdict: z.string().describe('The verdict generated by traversing the decision tree.'),
  }),
  execute: async ({ verdict }, toolContext) => {
    // Track the number of validation attempts in the session state
    let attempts = toolContext?.state.get<number>('VALIDATION_ATTEMPTS') || 0;
    attempts = attempts + 1;
    if (toolContext) {
      toolContext.state.set(VALIDATION_ATTEMPTS_KEY, attempts);
    }

    if (attempts >= MAX_ITERATIONS) {
      console.log(`Max validation attempts reached (${attempts}). Forcing LLM to terminate.`);
      if (toolContext) {
        // Break the internal LLM tool-calling loop
        toolContext.actions.escalate = true;
      }
      return {
        status: 'FATAL_ERROR',
        message: `STOP processing immediately and output the final JSON schema with verdict: "None".`,
      };
    }

    if (verdict === 'None') {
      return {
        status: 'ERROR',
        message:
          "You failed to traverse the decision tree. You must select a valid architecture. Do not output 'None'.",
      };
    }

    return {
      status: 'SUCCESS',
      message: 'Verdict is valid. You may now generate the final output schema and finish.',
    };
  },
});

const beforeModelCallback: BeforeModelCallback = async ({ context }) => {
  // If we already have a valid decision (e.g., from a previous loop iteration), stop the loop.
  const { decision } = getEvaluationContext(context);
  if (decision && decision.verdict !== 'None') {
    return {
      content: {
        role: 'model',
        parts: [
          {
            text: JSON.stringify(decision),
          },
        ],
      },
    };
  }

  const { project, antiPatterns } = getEvaluationContext(context);

  console.log('in evaluation -> beforeModelCallback');
  const { isCompleted } = isProjectDetailsFilled(project);

  if (isCompleted && antiPatterns) {
    return undefined;
  }

  // Short-circuit if project is incomplete, and escalate to break the loop.
  // context.actions.escalate = true;
  return {
    content: {
      role: 'model',
      parts: [
        {
          text: JSON.stringify({
            verdict: 'None',
            nodes: [],
          }),
        },
      ],
    },
  };
};

export function createDecisionTreeAgent(model: string) {
  const decisionTreeAgent = new LlmAgent({
    name: 'DecisionTreeAgent',
    model,
    description:
      'Evaluates the structured project components against the Agent Fundamentals decision tree to determine the optimal architectural solution (e.g., Use Agent, Use LLM, Use Workflow Automation, or Use Simple API).',
    beforeModelCallback,
    instruction: (context) => {
      const { project, antiPatterns } = getEvaluationContext(context);
      const { isCompleted } = isProjectDetailsFilled(project);
      if (project && isCompleted && antiPatterns) {
        return generateDecisionPrompt(project);
      }

      return 'Skipping LLM due to incomplete INTENT data.';
    },
    tools: [validateDecisionTool],
    outputSchema: decisionSchema,
    outputKey: DECISION_KEY,
  });

  return decisionTreeAgent;
}
